### ISSUE TITLE
There are a lot of such errors in the logs. Failed to load boss item brutalbosses:

### ISSUE THREAD

**Issue by RIZ79** [someaddons/dungeonbosses#2]
**Describe the bug**
There are a lot of such errors in the logs. Failed to load boss item brutalbosses:

**To Reproduce**

**Expected behavior**

** Mod version **
2.2

** Logs **
Latest/Crash log
[2022-01-23-4.log.gz](https://github.com/someaddons/dungeonbosses/files/7921533/2022-01-23-4.log.gz)

**Comment by someaddons** [comment]
That is apoheosis scanning the custom bosses folder of this mod, just because it is called "bosses". Aka not something this mod causes nor I got control over, so please make a bug report to apotheosis.
Related code line of it: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/deadly/reload/BossItemManager.java#L61

**Comment by RIZ79** [comment]
sent
