### ISSUE TITLE
[1.18.2] Server Stops Ticking After Boss Spawn

### ISSUE THREAD

**Issue by HockeyZman2000** [someaddons/dungeonbosses#26]
Hoping you can help me find the cause of this. I'll be playing on my world for a random amount of time, and it will eventually cease to load new chunks, tick entities, and blocks don't drop when mined. After reviewing the debug log, this occurs in tandem when the line below appears and any variation of it:

[08May2022 00:46:33.371] [Worker-Main-19/DEBUG] [com.brutalbosses.BrutalBosses/]: Spawning brutalbosses:vindicatorboss at BlockPos{x=-280, y=69, z=35} at Chest with:minecraft:chests/pillager_outpost in minecraft:village

This has happened across multiple worlds I've tried to play, with different bosses each time. Not sure if it's a mod incompatibility or a weird error in the code but the game doesn't crash from it either. I've attached the latest log and debug log below

[debug.log](https://github.com/someaddons/dungeonbosses/files/8646410/debug.log)

[latest.log](https://github.com/someaddons/dungeonbosses/files/8646411/latest.log)

**Comment by HockeyZman2000** [comment]
Here is a list of all installed mods as well:
[modlist-08-05-2022_01.09.39.txt](https://github.com/someaddons/dungeonbosses/files/8646420/modlist-08-05-2022_01.09.39.txt)

**Comment by someaddons** [comment]
brutal bosses doesnt do anything to cause behaviour like that, its just a coincidence with the log message. The message appears during structures beeing spawned in, so its likely that worldgen is stalling. So mostly likely candidates from your modlist would be rubidium(performance mod which often got trouble), starlight(involved in worldgen light updates) and terralith.

I'd also suggest to setup a local server and put your world on there, because the server will crash after beeing stalled for X time unlike the client. That crash then shows where its stalled

**Comment by RAIMBOWFISH** [comment]
Hello, I had the same issue of the world stops ticking at some point after joining the world. For me, getting rid of Champions out of my mod pack fixed the issue and it didn't occur even with brutal bosses installed after I removed champions.

I've attached a text file of mods in my mod pack. The champions mod caused this crash even with most world gen mods removed, including terralif
