### ISSUE TITLE
If you change the visual scale, it does not change their hitbox.

### ISSUE THREAD

**Issue by JetpackRescue** [someaddons/dungeonbosses#3]
1.16.5
I changed the blazeboss visualscale, but it doesn't change their hitbox so you have to shoot below the mob. Any time you shoot the mob it misses because the hitbox is tiny below him. Is there a way to add a change to the hitbox as well?

Even changing the evoker to visualscale 1.5 makes it so the hitbox is below his head, i'm making a modpack with guns so the headshot multiplier is important, and they look more boss-like being bigger.

**Comment by someaddons** [comment]
The hitboxes are changed clientside, which is why it works for melee hits but any projectiles are calculated on server side and thus use the original sized hitbox. The reason why the serverside hitbox is not modified is that entities would have a hard time moving around whenthe hitbox varies from its normal size, so not really something I could nicely change.
